import 'package:mocktail/mocktail.dart';
import 'package:test/test.dart';

import '../../../../../../../../bin/src/features/auth/domain/use_cases/create_access_jwt/create_access_jwt_use_case.dart';
import '../../../../../../../../bin/src/features/auth/utils/constants/jwt_duration_constants.dart';
import '../../../../../../../../bin/src/wrappers/libraries/dart_jsonwebtoken/dart_jsonwebtoken_wrapper.dart';

void main() {
  final dartJsonWebTokenWrapper = _MockDartJsonWebTokenWrapper();

  // tested class
  final createJwtAccessTokenUseCase =
      CreateAccessJwtUseCase(dartJsonWebTokenWrapper: dartJsonWebTokenWrapper);

  setUpAll(() {
    registerFallbackValue(Duration());
  });

  tearDown(() {
    reset(dartJsonWebTokenWrapper);
  });

// TODO this should be called JWTAccess - no token in name
  group("$CreateAccessJwtUseCase", () {
    group(".call()", () {
      test(
        "given authId and playerId are provided"
        "when .call() is called"
        "then should return jwt generated by DartJsonWebTokenWrapper",
        () async {
          // setup
          when(() => dartJsonWebTokenWrapper.sign(
                payload: any(named: "payload"),
                expiresIn: any(named: "expiresIn"),
              )).thenReturn("jwt");

          // given
          final authId = "authId";
          final playerId = "playerId";

          // when
          final jwt = createJwtAccessTokenUseCase(
            authId: authId,
            playerId: playerId,
          );

          // then
          expect(jwt, equals("jwt"));
          verify(() => dartJsonWebTokenWrapper.sign(
                payload: {
                  "authId": authId,
                  "playerId": playerId,
                },
                expiresIn: JwtDurationConstants.ACCESS_TOKEN_DURATION.value,
              )).called(1);

          // cleanup
        },
      );

      // should generate jwt token that expires in custom provided duration
      test(
        "given custom duration is provided"
        "when .call() is called"
        "then should call DartJsonWebTokenWrapper.call with the provided custom duration value",
        () async {
          // setup
          when(() => dartJsonWebTokenWrapper.sign(
                payload: any(named: "payload"),
                expiresIn: any(named: "expiresIn"),
              )).thenReturn("jwt");

          // given
          final authId = "authId";
          final playerId = "playerId";
          final customDuration = Duration(days: 1);

          // when
          createJwtAccessTokenUseCase(
            authId: authId,
            playerId: playerId,
            expiresIn: customDuration,
          );

          // then
          verify(() => dartJsonWebTokenWrapper.sign(
                payload: {
                  "authId": authId,
                  "playerId": playerId,
                },
                expiresIn: customDuration,
              )).called(1);

          // cleanup
        },
      );
    });
  });
}

class _MockDartJsonWebTokenWrapper extends Mock
    implements DartJsonWebTokenWrapper {}
